### ISSUE TITLE
🐞 Bug - `aa4mg` Android 11/12 - Incorrect `phenotype.db` permissions

### ISSUE THREAD

**Issue by answer35** [Rikj000/Android-Auto-XLauncher-Unlocked#3] opened 2023-04-12 14:59 UTC
Hi, I'm using aa4mg and followed the instructions to install XLauncher, I have LSPosed enabled, Shamiko OK, and module enable in LSPosed. XLauncher has been installed using KingInstaller as described but still when I install OsmAnd or HereWeGo or HomeAssistant, those apps are listed in the About/Version into AA but not showing in launcher apps list. I don't know what I missed here :/

**Comment by Rikj000** [comment] 2023-04-12 15:09
Linking to: https://github.com/sn-00-x/aa4mg/issues/1

**Comment by Rikj000** [comment] 2023-04-12 15:22
Hi @answer35,

> ... but still when I install OsmAnd or HereWeGo or HomeAssistant, 
> those apps are listed in the About/Version into AA but not showing in launcher apps list.
> I don't know what I missed here :/

How did you install `OsmAnd`, `HereWeGo` and `HomeAssistant`?

You did not mention it, but I assume you've enabled developer mode + checked `unknown sources` in the AA app?

Also, all apps you want to use in AA, should be installed "from the Google Play Store".
Easiest way to do this, is through [KingInstaller](https://github.com/fcaronte/KingInstaller).

I'd recommend to use the "Check `Enable if you use rooted (LineageOS) phone` " option in KingInstaller,   
since I've implemented and tested that feature myself recently.

You can verify if apps are installed correctly [as described here](https://github.com/fcaronte/KingInstaller#verify-app-installation).

Additionally,
[here is a write-up/guide](https://forum.xda-developers.com/t/screen2auto-new-app-for-aa-smartphone-mirroring-only-for-root-devices.4062787/post-88392893) to all known levels of restrictions AA has for 3th party apps, and the by-passes that exist.
*(To my knowledge internal package rename is only required for S2A, and definitely not required for OsmAnd)*

And finally,
in the [AAXLU](https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked) Xposed module, you only need to check `Enable module` and check `Android Auto`,
checking other apps doesn't hurt, but it's not required / not preferred.

Hope that this info will be enough to unlock all 3th party apps on your phone as well.
Be sure to let me & the others reading know how it goes! :slightly_smiling_face:

**Comment by answer35** [comment] 2023-04-12 15:40
> How did you install `OsmAnd`, `HereWeGo` and `HomeAssistant`?

I installed using KingInstaller

> You did not mention it, but I assume you've enabled developer mode + checked `unknown sources` in the AA app?

Developper mode and unknown sources are enabled in AA App

> Also, all apps you want to use in AA, should be installed "from the Google Play Store". Easiest way to do this, is through [KingInstaller](https://github.com/fcaronte/KingInstaller).

Here I have FakeStore (because of MicroG I suppose ?)

> I'd recommend to use the "Check `Enable if you use rooted (LineageOS) phone` " option in KingInstaller, since I've implemented and tested that feature myself recently.

With that option it keeps being install from "FakeStore"

**Comment by Rikj000** [comment] 2023-04-12 16:04
Very strange, sounds like you've done all steps correctly.. :thinking: 

> Here I have FakeStore (because of MicroG I suppose ?)

FakeStore is fine, that's "the Google Play Store" on MicroG devices.

Next things which come to mind to check/try are:
- Unpatch + Re-patch the desired 3th party custom apps in [AA-Tweaker](https://github.com/shmykelsa/AA-Tweaker)
- Validate if the `phenotype.db` patches by AA-Tweaker's [patchforapps()](https://github.com/shmykelsa/AA-Tweaker/blob/master/app/src/main/java/sksa/aa/tweaker/MainActivity.java#L1645) function are applied under:
`/data/data/com.google.android.gms/databases/phenotype.db`
Open the file with an SQLite editor and check the `FlagOverrides` table,
point of interest being the `stringVal` of `app_white_list` (all your 3th party apps) and `app_black_list` (empty).
I can recommend [MiXplorer's Magisk Module](https://github.com/Magisk-Modules-Alt-Repo/MiXplorer) for this, which contains a SQLite editor plugin.

Last resort **only recommended for MicroG devices:**:
- Delete your Android Auto data + uninstall it's updates
- Delete the `/data/data/com.google.android.gms/databases/phenotype.db` file *(not used by MicroG anyways)*
- Uninstall any old versions of aa4mg and AAXLU if you have them
- Reboot
- Install [aa4mg v0.5.1-a13](https://github.com/Rikj000/AndroidAuto4MicroG/releases) *(for now only available on my fork, still waiting for the official merge)*,   
    be sure to follow the corresponding [installation](https://github.com/Rikj000/AndroidAuto4MicroG#installation) steps

This will assure that your AA app data will be clean + installed as required *(phenotype.db, permissions, etc...)*

**Comment by answer35** [comment] 2023-04-13 09:59
I was also thinking about using your fork of aa4mg but I am using OOS11 based ROM so I am not able to use it. Do you think it could be the issue ? That I am using A11 maybe ?

Also I am not using AA-Tweaker, everytime I tried to use it, it gave me an error that it couldn't do the tweak. Don't remember the message exactly, I could try again if you believe it is necessary.

**Comment by Rikj000** [comment] 2023-04-13 10:39
Interesting!

> I was also thinking about using your fork of aa4mg but I am using OOS11 based ROM so I am not able to use it.
> Do you think it could be the issue ? That I am using A11 maybe ?

First of all,   
**never use** `aa4mg` vX.X.X **-a13** releases on an Android 11 device.
For Android 11 you need a vX.X.X **-a11** build/release of `aa4mg`

I've already applied some of my changes to the [`a11`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a11) and [`a12`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a12) branches of [my `aa4mg` support fork](https://github.com/Rikj000/AndroidAuto4MicroG),   
but they are still a fair amount of commits / changes behind the current [`a13`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a13) branch. 

Especially [this bugfix](https://github.com/Rikj000/AndroidAuto4MicroG/commit/26e277e8207643516c8af451ba3415c1517d985f), has not been applied to the [`a11`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a11) and [`a12`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a12) branches yet.
Which might be the cause of below AA-Tweaker issues.

I will bring the latest changes to the [`a11`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a11) and [`a12`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a12) branches tonight,   
and will keep you posted when you can test.

Keep in mind that I will not able to test A11/A12 due to not having such a device available to me.

> Also I am not using AA-Tweaker, everytime I tried to use it, it gave me an error that it couldn't do the tweak.
> Don't remember the message exactly, I could try again if you believe it is necessary.

Sounds like the file/folder permissions/ownership aren't correct on your device,   
please validate if this file + folder are configured correctly / as following:

<details>
  <summary markdown="block">
  Click to expand/collapse file + folder screenshots
  </summary>

![Screenshot-folder.png](https://user-images.githubusercontent.com/24852597/231734350-21a50653-e1b8-4c48-bb2b-db44fc1987e1.png)
![Screenshot-file.png](https://user-images.githubusercontent.com/24852597/231734400-e767481b-6abb-4234-8fcd-d8a0226e5ba8.png)

</details>

**Comment by answer35** [comment] 2023-04-13 11:41
I have some differences on those permissions:

<details>
  <summary markdown="block">
  Click to expand/collapse file + folder screenshots
  </summary>

![Screenshot_20230413-133726_MiXplorer](https://user-images.githubusercontent.com/26594746/231747778-dce1a48f-4afb-482e-bd9d-9fb171df6178.png)

![Screenshot_20230413-133757_MiXplorer](https://user-images.githubusercontent.com/26594746/231747856-527fff65-34e0-4009-be84-5c190abfc9a8.png)

![Screenshot_20230413-133820_MiXplorer](https://user-images.githubusercontent.com/26594746/231747889-8b92938d-5f17-4d86-8c59-06f7477c5cc4.png)

</details>

**Comment by answer35** [comment] 2023-04-13 12:38
Just in case, I've made the steps you asked before but using sn-00-x A11 version of aa4mg. I followed the installation steps you've made but still got the same issue with apps not available in app launcher. but listed in version section :/ Also, I checked files permission, phenotype.db isn't there and phenotype folder has same permission as before which looks ok.

Edit: My bad, forgot to install XLauncher-Unlock again with KingInstaller. Installed it, reboot and now it's here :) will try this evening in car :) Thanks for your help. I will close issue this evening after testing in car ;)

**Comment by Rikj000** [comment] 2023-04-13 15:17
> I have some differences on those permissions:
> Click to expand/collapse file + folder screenshots

In your 3th screenshot I notice an issue with the `phenotype.db` file,
on MicroG, the group/owner should be `microG Services Core` as in my 2nd screenshot.

> Edit: My bad, forgot to install XLauncher-Unlock again with KingInstaller. Installed it, reboot and now it's here :) will try this evening in car :) Thanks for your help. I will close issue this evening after testing in car ;)

Please don't close this issue yet!
Just finished my day-time job,   
now I'll start with bringing the [`a11`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a11) and [`a12`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a12) branches up to date with the latest [`a13`](https://github.com/Rikj000/AndroidAuto4MicroG/tree/a13) changes.

I'll ping you once there is a new version ready for you to test, which should:
- Resolve the `phenotype.db` permission issue
- Add automatic dependency stub installation
- Allow to choose which stubs to (not) install
- Auto install AAXLU together with aa4mg

**Comment by Rikj000** [comment] 2023-04-13 20:20
@answer35 the I've released `v0.5.1` versions of `aa4mg` for Android 11/12! :tada: 

Please try as following and report how it goes:
1. Uninstall current AAXLU
2. Uninstall current AA updates
3. Uninstall current aa4mg
4. Install the `aa4mg-v0.5.1-a11-pre-release.zip` from the new [`v0.5.1`](https://github.com/Rikj000/AndroidAuto4MicroG/releases/tag/v0.5.1) release on my fork.

I've tested both the Android 11/12 releases in an AVD, there all worked correctly! :slightly_smiling_face:

**Comment by answer35** [comment] 2023-04-14 08:26
Yes it works great, I was also surprised that you added all stub apps to the install but that's a nice feature also :) and then after enabling AAXlauncher in LSPosed everything worked out of the box. Thanks for the great work :) I leave you decide to close the issue or not if you need me to test anything else maybe.

**Comment by Rikj000** [comment] 2023-04-14 10:03
Thank you for your feedback, happy too hear that all works nicely now! 😊 
Will close this issue because it's been resolved 🙂

**Closed as completed by Rikj000** 2023-04-14 10:03 UTC
Labels: Bug
