### ISSUE TITLE
❓ Question - Unrooted phone?

### ISSUE THREAD

**Issue by ZM71** [Rikj000/Android-Auto-XLauncher-Unlocked#10] opened 2024-12-21 14:42 UTC
Is this possible for unrooted and without bricking Android Auto?

**Comment by Rikj000** [comment] 2024-12-21 14:54
Duplicate of #7

And there is zero risk of bricking Android Auto.

**Closed as completed by Rikj000** 2024-12-21 14:54 UTC
Labels: Question

**Comment by ZM71** [comment] 2024-12-21 18:31
that did not even answer my question if i can brick my phone and if this works unrooted.
